//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Portal.Extensions.AzurePortalExtension.Client
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClientResources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClientResources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Portal.Extensions.AzurePortalExtension.Client.ClientResources", typeof(ClientResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        public static string AccessTitle
        {
            get
            {
                return ResourceManager.GetString("AccessTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string AssetPropertyNames_CloudService_Location
        {
            get
            {
                return ResourceManager.GetString("AssetPropertyNames_CloudService_Location", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource group.
        /// </summary>
        public static string AssetPropertyNames_Resource_ResourceGroup
        {
            get
            {
                return ResourceManager.GetString("AssetPropertyNames_Resource_ResourceGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to my resources.
        /// </summary>
        public static string AssetTypeNames_Resource_lowerPlural
        {
            get
            {
                return ResourceManager.GetString("AssetTypeNames_Resource_lowerPlural", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to my resource.
        /// </summary>
        public static string AssetTypeNames_Resource_lowerSingular
        {
            get
            {
                return ResourceManager.GetString("AssetTypeNames_Resource_lowerSingular", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to My Resources.
        /// </summary>
        public static string AssetTypeNames_Resource_plural
        {
            get
            {
                return ResourceManager.GetString("AssetTypeNames_Resource_plural", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to My Resource.
        /// </summary>
        public static string AssetTypeNames_Resource_singular
        {
            get
            {
                return ResourceManager.GetString("AssetTypeNames_Resource_singular", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Items From Controller.
        /// </summary>
        public static string CollectionPartTitle
        {
            get
            {
                return ResourceManager.GetString("CollectionPartTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        public static string ConfigurationLensTitle
        {
            get
            {
                return ResourceManager.GetString("ConfigurationLensTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create a new resource group.
        /// </summary>
        public static string CreateNewResourceGroup
        {
            get
            {
                return ResourceManager.GetString("CreateNewResourceGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter the name.
        /// </summary>
        public static string EnterTheName
        {
            get
            {
                return ResourceManager.GetString("EnterTheName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AzurePortalExtension.
        /// </summary>
        public static string ExtensionName
        {
            get
            {
                return ResourceManager.GetString("ExtensionName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quick start.
        /// </summary>
        public static string GetStartedLensTitle
        {
            get
            {
                return ResourceManager.GetString("GetStartedLensTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to http://msdn.microsoft.com.
        /// </summary>
        public static string htmlSiteMSDNAddress
        {
            get
            {
                return ResourceManager.GetString("htmlSiteMSDNAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Key
        {
            get
            {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage keys.
        /// </summary>
        public static string keyManagementBladeTitle
        {
            get
            {
                return ResourceManager.GetString("keyManagementBladeTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Primary Key.
        /// </summary>
        public static string keyManagementPrimaryTitle
        {
            get
            {
                return ResourceManager.GetString("keyManagementPrimaryTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Secondary Key.
        /// </summary>
        public static string keyManagementSecondaryTitle
        {
            get
            {
                return ResourceManager.GetString("keyManagementSecondaryTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Keys.
        /// </summary>
        public static string keyManagementShortTitle
        {
            get
            {
                return ResourceManager.GetString("keyManagementShortTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Keys.
        /// </summary>
        public static string keyManagementTitle
        {
            get
            {
                return ResourceManager.GetString("keyManagementTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Link Property Label.
        /// </summary>
        public static string LinkPropertyLabel
        {
            get
            {
                return ResourceManager.GetString("LinkPropertyLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Link Property Value.
        /// </summary>
        public static string LinkPropertyValue
        {
            get
            {
                return ResourceManager.GetString("LinkPropertyValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingText
        {
            get
            {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to www.microsoft.com.
        /// </summary>
        public static string MicrosoftUri
        {
            get
            {
                return ResourceManager.GetString("MicrosoftUri", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        public static string MonitoringLensTitle
        {
            get
            {
                return ResourceManager.GetString("MonitoringLensTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string OperationLensTitle
        {
            get
            {
                return ResourceManager.GetString("OperationLensTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Or create new.
        /// </summary>
        public static string OrCreateNew
        {
            get
            {
                return ResourceManager.GetString("OrCreateNew", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Or select existing.
        /// </summary>
        public static string OrSelectExisting
        {
            get
            {
                return ResourceManager.GetString("OrSelectExisting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        public static string Package
        {
            get
            {
                return ResourceManager.GetString("Package", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select a location.
        /// </summary>
        public static string PleaseSelectLocation
        {
            get
            {
                return ResourceManager.GetString("PleaseSelectLocation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select or enter a resource group.
        /// </summary>
        public static string PleaseSelectResourceGroup
        {
            get
            {
                return ResourceManager.GetString("PleaseSelectResourceGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select a subscription.
        /// </summary>
        public static string PleaseSelectSubscription
        {
            get
            {
                return ResourceManager.GetString("PleaseSelectSubscription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string PropertiesBladeTitle
        {
            get
            {
                return ResourceManager.GetString("PropertiesBladeTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quick Start Blade Subtitle.
        /// </summary>
        public static string QuickStartBladeSubtitle
        {
            get
            {
                return ResourceManager.GetString("QuickStartBladeSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quick Start Blade Title.
        /// </summary>
        public static string QuickStartBladeTitle
        {
            get
            {
                return ResourceManager.GetString("QuickStartBladeTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quick Start Description.
        /// </summary>
        public static string QuickStartDescription
        {
            get
            {
                return ResourceManager.GetString("QuickStartDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This section has an Icon and will open a new browser tab on click. These two factors are mutually exclusive as the first depends on if an iconUri is set and the second because section.selectable was populated. This description text is multiline..
        /// </summary>
        public static string QuickStartInfoListDesc1
        {
            get
            {
                return ResourceManager.GetString("QuickStartInfoListDesc1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PDL provides openBlades and links[] of the InfoListBladeLinkContract type will be opened in blades. The tile supports both blade links and hyperlinks in the same section. Numbers are used when iconUri is not set..
        /// </summary>
        public static string QuickStartInfoListDesc2
        {
            get
            {
                return ResourceManager.GetString("QuickStartInfoListDesc2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Icon &amp; Selectable.
        /// </summary>
        public static string QuickStartInfoListTitle1
        {
            get
            {
                return ResourceManager.GetString("QuickStartInfoListTitle1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Section that opens blade.
        /// </summary>
        public static string QuickStartInfoListTitle2
        {
            get
            {
                return ResourceManager.GetString("QuickStartInfoListTitle2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quick Start.
        /// </summary>
        public static string QuickStartShortTitle
        {
            get
            {
                return ResourceManager.GetString("QuickStartShortTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quick Start.
        /// </summary>
        public static string QuickStartTitle
        {
            get
            {
                return ResourceManager.GetString("QuickStartTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Regenerate {keyType} key on resource {resource} failed.
        /// </summary>
        public static string regenerateKeyFailureNotificationMessage
        {
            get
            {
                return ResourceManager.GetString("regenerateKeyFailureNotificationMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Regenerate Key Failed.
        /// </summary>
        public static string regenerateKeyFailureNotificationTitle
        {
            get
            {
                return ResourceManager.GetString("regenerateKeyFailureNotificationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Regenerate {keyType} key on resource {resource} completed successfully.
        /// </summary>
        public static string regenerateKeySuccessNotificationMessage
        {
            get
            {
                return ResourceManager.GetString("regenerateKeySuccessNotificationMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Regenerate Key Successful.
        /// </summary>
        public static string regenerateKeySuccessNotificationTitle
        {
            get
            {
                return ResourceManager.GetString("regenerateKeySuccessNotificationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Regenerate Primary.
        /// </summary>
        public static string RegeneratePrimary
        {
            get
            {
                return ResourceManager.GetString("RegeneratePrimary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to regenerate the Primary key for {0}.
        /// </summary>
        public static string regeneratePrimaryKeyConfirmMessage
        {
            get
            {
                return ResourceManager.GetString("regeneratePrimaryKeyConfirmMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Regenerate Secondary.
        /// </summary>
        public static string RegenerateSecondary
        {
            get
            {
                return ResourceManager.GetString("RegenerateSecondary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to regenerate the Secondary key for {0}.
        /// </summary>
        public static string regenerateSecondaryKeyConfirmMessage
        {
            get
            {
                return ResourceManager.GetString("regenerateSecondaryKeyConfirmMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Regenerating access key ....
        /// </summary>
        public static string RegeneratingKeyInProgressTitle
        {
            get
            {
                return ResourceManager.GetString("RegeneratingKeyInProgressTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region
        {
            get
            {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource Subtitle.
        /// </summary>
        public static string ResourceBladeSubtitle
        {
            get
            {
                return ResourceManager.GetString("ResourceBladeSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource Title.
        /// </summary>
        public static string ResourceBladeTitle
        {
            get
            {
                return ResourceManager.GetString("ResourceBladeTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource group name can only include alphanumeric characters, periods, underscores, hyphens and parenthesis and cannot end in a period..
        /// </summary>
        public static string ResourceGroupNameInvalidMessage
        {
            get
            {
                return ResourceManager.GetString("ResourceGroupNameInvalidMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource group name only allows up to 64 characters..
        /// </summary>
        public static string ResourceGroupNameLengthValidationMessage
        {
            get
            {
                return ResourceManager.GetString("ResourceGroupNameLengthValidationMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource Lens Title.
        /// </summary>
        public static string ResourceLensTitle
        {
            get
            {
                return ResourceManager.GetString("ResourceLensTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string ResourceLocationColumn
        {
            get
            {
                return ResourceManager.GetString("ResourceLocationColumn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource Name.
        /// </summary>
        public static string ResourceName
        {
            get
            {
                return ResourceManager.GetString("ResourceName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ResourceNameColumn
        {
            get
            {
                return ResourceManager.GetString("ResourceNameColumn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The resource name is required.
        /// </summary>
        public static string ResourceNameRequired
        {
            get
            {
                return ResourceManager.GetString("ResourceNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ResourceStatusColumn
        {
            get
            {
                return ResourceManager.GetString("ResourceStatusColumn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string RolesTitle
        {
            get
            {
                return ResourceManager.GetString("RolesTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a location.
        /// </summary>
        public static string SelectLocation
        {
            get
            {
                return ResourceManager.GetString("SelectLocation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to (Optional) Select a package.
        /// </summary>
        public static string SelectPackage
        {
            get
            {
                return ResourceManager.GetString("SelectPackage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a resource group.
        /// </summary>
        public static string SelectResourceGroup
        {
            get
            {
                return ResourceManager.GetString("SelectResourceGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a subscription.
        /// </summary>
        public static string SelectSubscription
        {
            get
            {
                return ResourceManager.GetString("SelectSubscription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings
        {
            get
            {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start Board Tile Description.
        /// </summary>
        public static string StartBoardPartDescription
        {
            get
            {
                return ResourceManager.GetString("StartBoardPartDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start Board Tile.
        /// </summary>
        public static string StartBoardPartTitle
        {
            get
            {
                return ResourceManager.GetString("StartBoardPartTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status
        {
            get
            {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        public static string Subscription
        {
            get
            {
                return ResourceManager.GetString("Subscription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Subscription Id.
        /// </summary>
        public static string SubscriptionId
        {
            get
            {
                return ResourceManager.GetString("SubscriptionId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Subscription Name.
        /// </summary>
        public static string SubscriptionName
        {
            get
            {
                return ResourceManager.GetString("SubscriptionName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TagsTitle
        {
            get
            {
                return ResourceManager.GetString("TagsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text Property Label.
        /// </summary>
        public static string TextPropertyLabel
        {
            get
            {
                return ResourceManager.GetString("TextPropertyLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        public static string UsageLensTitle
        {
            get
            {
                return ResourceManager.GetString("UsageLensTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UsersTitle
        {
            get
            {
                return ResourceManager.GetString("UsersTitle", resourceCulture);
            }
        }
    }
}
