/**
 * @file Source code generated by PDL compiler.
 * @version 1.0
 * @sdkversion 5.0.302.329 (production_sdk#b7c08d1.160414-1450)
 * @schemaversion 1.0.0.2
 */
/// <reference path="../TypeReferences.d.ts" />

export = BladeDefinitions;
module BladeDefinitions {
    var extensionName: string = "AzurePortalExtension";
    export interface PropertiesBladeInputs {
        id: any;
    }
    export class PropertiesBladeReference extends MsPortalFx.Composition.PdlBladeReference<PropertiesBladeInputs> {
        public constructor(inputs: PropertiesBladeInputs) {
            super("PropertiesBlade", inputs, undefined, undefined, extensionName);
        }
    }
    export interface ResourceBladeInputs {
        id: any;
    }
    export class ResourceBladeReference extends MsPortalFx.Composition.PdlBladeReference<ResourceBladeInputs> {
        public constructor(inputs: ResourceBladeInputs) {
            super("ResourceBlade", inputs, undefined, undefined, extensionName);
        }
    }
    export class QuickStartBladeReference extends MsPortalFx.Composition.PdlBladeReference<void> {
        public constructor() {
            super("QuickStartBlade", undefined, undefined, undefined, extensionName);
        }
    }
    export interface SettingsBladeInputs {
        id: any;
    }
    export class SettingsBladeReference extends MsPortalFx.Composition.PdlBladeReference<SettingsBladeInputs> {
        public constructor(inputs: SettingsBladeInputs) {
            super("SettingsBlade", inputs, undefined, undefined, extensionName);
        }
    }
    export class CreateBladeReference extends MsPortalFx.Composition.ParameterProviderBladeReference<void, any, any> {
        public constructor(options: MsPortalFx.Composition.ParameterProviderOptions<any, any>) {
            super(options, "CreateBlade", undefined, extensionName);
        }
    }
}
