/**
 * @file Source code generated by PDL compiler.
 * @version 1.0
 * @sdkversion 5.0.302.319 (production_sdk#058d65f.160330-1230)
 * @schemaversion 1.0.0.2
 */
/// <reference path="../TypeReferences.d.ts" />
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
define(["require", "exports"], function (require, exports) {
    var ViewModelFactories;
    (function (ViewModelFactories) {
        var BrowseViewModelFactoriesBase = (function (_super) {
            __extends(BrowseViewModelFactoriesBase, _super);
            function BrowseViewModelFactoriesBase() {
                _super.apply(this, arguments);
            }
            BrowseViewModelFactoriesBase.prototype.ResourcePartViewModel = function (container, initialState) {
                var _this = this;
                return this.loadViewModelAsync("../Browse/ViewModels/ResourcePartViewModel", function (providerModule) { return new providerModule.ResourcePartViewModel(container, initialState, _this.dataContext); }, require);
            };
            BrowseViewModelFactoriesBase.prototype.AssetTypeViewModel = function (container, initialState) {
                var _this = this;
                return this.loadViewModelAsync("../Browse/ViewModels/AssetTypeViewModel", function (providerModule) { return new providerModule.AssetTypeViewModel(container, initialState, _this.dataContext); }, require);
            };
            return BrowseViewModelFactoriesBase;
        })(FxImpl.Extension.ViewModelAreaFactoriesBase);
        ViewModelFactories.BrowseViewModelFactoriesBase = BrowseViewModelFactoriesBase;
        var ResourceViewModelFactoriesBase = (function (_super) {
            __extends(ResourceViewModelFactoriesBase, _super);
            function ResourceViewModelFactoriesBase() {
                _super.apply(this, arguments);
            }
            ResourceViewModelFactoriesBase.prototype.PropertiesBladeViewModel = function (container, initialState) {
                var _this = this;
                return this.loadViewModelAsync("../Resource/Properties/ViewModels/PropertiesBladeViewModel", function (providerModule) { return new providerModule.PropertiesBladeViewModel(container, initialState, _this.dataContext); }, require);
            };
            ResourceViewModelFactoriesBase.prototype.PropertiesPartViewModel = function (container, initialState) {
                var _this = this;
                return this.loadViewModelAsync("../Resource/Properties/ViewModels/PropertiesPartViewModel", function (providerModule) { return new providerModule.PropertiesPartViewModel(container, initialState, _this.dataContext); }, require);
            };
            ResourceViewModelFactoriesBase.prototype.ApiAccountSpecPickerBladeViewModel = function (container, initialState) {
                var _this = this;
                return this.loadViewModelAsync("../Resource/Pricing/ViewModels/ApiAccountSpecPickerBladeViewModel", function (providerModule) { return new providerModule.ApiAccountSpecPickerBladeViewModel(container, initialState, _this.dataContext); }, require);
            };
            ResourceViewModelFactoriesBase.prototype.ApiAccountSpecPickerExtender = function (container, initialState) {
                var _this = this;
                return this.loadViewModelAsync("../Resource/Pricing/ViewModels/ApiAccountSpecPickerExtender", function (providerModule) { return new providerModule.ApiAccountSpecPickerExtender(container, initialState, _this.dataContext); }, require);
            };
            ResourceViewModelFactoriesBase.prototype.KeySettingsBladeViewModel = function (container, initialState) {
                var _this = this;
                return this.loadViewModelAsync("../Resource/KeyManagement/ViewModels/KeySettingsBladeViewModel", function (providerModule) { return new providerModule.KeySettingsBladeViewModel(container, initialState, _this.dataContext); }, require);
            };
            ResourceViewModelFactoriesBase.prototype.KeysPropertiesPartViewModel = function (container, initialState) {
                var _this = this;
                return this.loadViewModelAsync("../Resource/KeyManagement/ViewModels/KeysPropertiesPartViewModel", function (providerModule) { return new providerModule.KeysPropertiesPartViewModel(container, initialState, _this.dataContext); }, require);
            };
            ResourceViewModelFactoriesBase.prototype.GeneratePrimaryCommandViewModel = function (container, initialState) {
                var _this = this;
                return this.loadViewModelAsync("../Resource/KeyManagement/ViewModels/GeneratePrimaryCommandViewModel", function (providerModule) { return new providerModule.GeneratePrimaryCommandViewModel(container, initialState, _this.dataContext); }, require);
            };
            ResourceViewModelFactoriesBase.prototype.GenerateSecondaryCommandViewModel = function (container, initialState) {
                var _this = this;
                return this.loadViewModelAsync("../Resource/KeyManagement/ViewModels/GenerateSecondaryCommandViewModel", function (providerModule) { return new providerModule.GenerateSecondaryCommandViewModel(container, initialState, _this.dataContext); }, require);
            };
            ResourceViewModelFactoriesBase.prototype.CognitiveServicesCreateBladeViewModel = function (container, initialState) {
                var _this = this;
                return this.loadViewModelAsync("../Resource/Create/ViewModels/CognitiveServicesCreateBladeViewModel", function (providerModule) { return new providerModule.CognitiveServicesCreateBladeViewModel(container, initialState, _this.dataContext); }, require);
            };
            ResourceViewModelFactoriesBase.prototype.CreationLegalBladeViewModel = function (container, initialState) {
                var _this = this;
                return this.loadViewModelAsync("../Resource/Create/ViewModels/CreationLegalBladeViewModel", function (providerModule) { return new providerModule.CreationLegalBladeViewModel(container, initialState, _this.dataContext); }, require);
            };
            ResourceViewModelFactoriesBase.prototype.CognitiveServicesApiTypeBladeViewModel = function (container, initialState) {
                var _this = this;
                return this.loadViewModelAsync("../Resource/Create/ViewModels/CognitiveServicesApiTypeBladeViewModel", function (providerModule) { return new providerModule.CognitiveServicesApiTypeBladeViewModel(container, initialState, _this.dataContext); }, require);
            };
            ResourceViewModelFactoriesBase.prototype.ApiTypePartViewModel = function (container, initialState) {
                var _this = this;
                return this.loadViewModelAsync("../Resource/Create/ViewModels/ApiTypePartViewModel", function (providerModule) { return new providerModule.ApiTypePartViewModel(container, initialState, _this.dataContext); }, require);
            };
            ResourceViewModelFactoriesBase.prototype.ResourceBladeViewModel = function (container, initialState) {
                var _this = this;
                return this.loadViewModelAsync("../Resource/Summary/ViewModels/ResourceBladeViewModel", function (providerModule) { return new providerModule.ResourceBladeViewModel(container, initialState, _this.dataContext); }, require);
            };
            ResourceViewModelFactoriesBase.prototype.ResourceSummaryPartViewModel = function (container, initialState) {
                var _this = this;
                return this.loadViewModelAsync("../Resource/Summary/ViewModels/ResourceSummaryPartViewModel", function (providerModule) { return new providerModule.ResourceSummaryPartViewModel(container, initialState, _this.dataContext); }, require);
            };
            ResourceViewModelFactoriesBase.prototype.QuickStartBladeViewModel = function (container, initialState) {
                var _this = this;
                return this.loadViewModelAsync("../Resource/QuickStart/ViewModels/QuickStartBladeViewModel", function (providerModule) { return new providerModule.QuickStartBladeViewModel(container, initialState, _this.dataContext); }, require);
            };
            ResourceViewModelFactoriesBase.prototype.QuickStartPartViewModel = function (container, initialState) {
                var _this = this;
                return this.loadViewModelAsync("../Resource/QuickStart/ViewModels/QuickStartPartViewModel", function (providerModule) { return new providerModule.QuickStartPartViewModel(container, initialState, _this.dataContext); }, require);
            };
            ResourceViewModelFactoriesBase.prototype.SettingsBladeViewModel = function (container, initialState) {
                var _this = this;
                return this.loadViewModelAsync("../Resource/Settings/ViewModels/SettingsBladeViewModel", function (providerModule) { return new providerModule.SettingsBladeViewModel(container, initialState, _this.dataContext); }, require);
            };
            ResourceViewModelFactoriesBase.prototype.SettingsPartViewModel = function (container, initialState) {
                var _this = this;
                return this.loadViewModelAsync("../Resource/Settings/ViewModels/SettingsPartViewModel", function (providerModule) { return new providerModule.SettingsPartViewModel(container, initialState, _this.dataContext); }, require);
            };
            ResourceViewModelFactoriesBase.prototype.BlankBladeBladeViewModel = function (container, initialState) {
                var _this = this;
                return this.loadViewModelAsync("../Resource/Settings/ViewModels/SettingsBladeViewModel", function (providerModule) { return new providerModule.BlankBladeBladeViewModel(container, initialState, _this.dataContext); }, require);
            };
            ResourceViewModelFactoriesBase.prototype.OxfordCreateBladeViewModel = function (container, initialState) {
                var _this = this;
                return this.loadViewModelAsync("../Resource/Create/ViewModels/OxfordCreateBladeViewModel", function (providerModule) { return new providerModule.OxfordCreateBladeViewModel(container, initialState, _this.dataContext); }, require);
            };
            ResourceViewModelFactoriesBase.prototype.OxfordApiTypeBladeViewModel = function (container, initialState) {
                var _this = this;
                return this.loadViewModelAsync("../Resource/Create/ViewModels/OxfordApiTypeBladeViewModel", function (providerModule) { return new providerModule.OxfordApiTypeBladeViewModel(container, initialState, _this.dataContext); }, require);
            };
            ResourceViewModelFactoriesBase.prototype.EventsPartAdapterViewModel = function (container, initialState) {
                var _this = this;
                return this.loadViewModelAsync("../Resource/Summary/ViewModels/EventsPartAdapterViewModel", function (providerModule) { return new providerModule.EventsPartAdapterViewModel(container, initialState, _this.dataContext); }, require);
            };
            ResourceViewModelFactoriesBase.prototype.PricingTierPartAdapterViewModel = function (container, initialState) {
                var _this = this;
                return this.loadViewModelAsync("../Resource/Summary/ViewModels/PricingTierPartAdapterViewModel", function (providerModule) { return new providerModule.PricingTierPartAdapterViewModel(container, initialState, _this.dataContext); }, require);
            };
            ResourceViewModelFactoriesBase.prototype.ApiAccountPricingTierV3LauncherExtender = function (container, initialState) {
                var _this = this;
                return this.loadViewModelAsync("../Resource/Pricing/ViewModels/ApiAccountPricingTierLauncherExtender", function (providerModule) { return new providerModule.ApiAccountPricingTierV3LauncherExtender(container, initialState, _this.dataContext); }, require);
            };
            ResourceViewModelFactoriesBase.prototype.SettingsCommandViewModel = function (container, initialState) {
                var _this = this;
                return this.loadViewModelAsync("../Resource/Summary/ViewModels/SettingsCommandViewModel", function (providerModule) { return new providerModule.SettingsCommandViewModel(container, initialState, _this.dataContext); }, require);
            };
            ResourceViewModelFactoriesBase.prototype.DeleteCommandViewModel = function (container, initialState) {
                var _this = this;
                return this.loadViewModelAsync("../Resource/Summary/ViewModels/DeleteCommandViewModel", function (providerModule) { return new providerModule.DeleteCommandViewModel(container, initialState, _this.dataContext); }, require);
            };
            return ResourceViewModelFactoriesBase;
        })(FxImpl.Extension.ViewModelAreaFactoriesBase);
        ViewModelFactories.ResourceViewModelFactoriesBase = ResourceViewModelFactoriesBase;
        var ViewModelFactoriesBase = (function () {
            function ViewModelFactoriesBase() {
            }
            ViewModelFactoriesBase.prototype.SetBrowseViewModelFactories = function (factories) {
                this._BrowseViewModelFactories = factories;
            };
            ViewModelFactoriesBase.prototype.Browse = function () {
                this._BrowseViewModelFactories = this._BrowseViewModelFactories || new BrowseViewModelFactoriesBase();
                return this._BrowseViewModelFactories;
            };
            ViewModelFactoriesBase.prototype.Browse$ResourcePartViewModel = function (container, initialState) {
                return this.Browse().ResourcePartViewModel(container, initialState);
            };
            ViewModelFactoriesBase.prototype.SetResourceViewModelFactories = function (factories) {
                this._ResourceViewModelFactories = factories;
            };
            ViewModelFactoriesBase.prototype.Resource = function () {
                this._ResourceViewModelFactories = this._ResourceViewModelFactories || new ResourceViewModelFactoriesBase();
                return this._ResourceViewModelFactories;
            };
            ViewModelFactoriesBase.prototype.Resource$PropertiesBladeViewModel = function (container, initialState) {
                return this.Resource().PropertiesBladeViewModel(container, initialState);
            };
            ViewModelFactoriesBase.prototype.Resource$PropertiesPartViewModel = function (container, initialState) {
                return this.Resource().PropertiesPartViewModel(container, initialState);
            };
            ViewModelFactoriesBase.prototype.Resource$ApiAccountSpecPickerBladeViewModel = function (container, initialState) {
                return this.Resource().ApiAccountSpecPickerBladeViewModel(container, initialState);
            };
            ViewModelFactoriesBase.prototype.Resource$ApiAccountSpecPickerExtender = function (container, initialState) {
                return this.Resource().ApiAccountSpecPickerExtender(container, initialState);
            };
            ViewModelFactoriesBase.prototype.Resource$KeySettingsBladeViewModel = function (container, initialState) {
                return this.Resource().KeySettingsBladeViewModel(container, initialState);
            };
            ViewModelFactoriesBase.prototype.Resource$KeysPropertiesPartViewModel = function (container, initialState) {
                return this.Resource().KeysPropertiesPartViewModel(container, initialState);
            };
            ViewModelFactoriesBase.prototype.Resource$GeneratePrimaryCommandViewModel = function (container, initialState) {
                return this.Resource().GeneratePrimaryCommandViewModel(container, initialState);
            };
            ViewModelFactoriesBase.prototype.Resource$GenerateSecondaryCommandViewModel = function (container, initialState) {
                return this.Resource().GenerateSecondaryCommandViewModel(container, initialState);
            };
            ViewModelFactoriesBase.prototype.Resource$CognitiveServicesCreateBladeViewModel = function (container, initialState) {
                return this.Resource().CognitiveServicesCreateBladeViewModel(container, initialState);
            };
            ViewModelFactoriesBase.prototype.Resource$CreationLegalBladeViewModel = function (container, initialState) {
                return this.Resource().CreationLegalBladeViewModel(container, initialState);
            };
            ViewModelFactoriesBase.prototype.Resource$CognitiveServicesApiTypeBladeViewModel = function (container, initialState) {
                return this.Resource().CognitiveServicesApiTypeBladeViewModel(container, initialState);
            };
            ViewModelFactoriesBase.prototype.Resource$ApiTypePartViewModel = function (container, initialState) {
                return this.Resource().ApiTypePartViewModel(container, initialState);
            };
            ViewModelFactoriesBase.prototype.Resource$ResourceBladeViewModel = function (container, initialState) {
                return this.Resource().ResourceBladeViewModel(container, initialState);
            };
            ViewModelFactoriesBase.prototype.Resource$ResourceSummaryPartViewModel = function (container, initialState) {
                return this.Resource().ResourceSummaryPartViewModel(container, initialState);
            };
            ViewModelFactoriesBase.prototype.Resource$QuickStartBladeViewModel = function (container, initialState) {
                return this.Resource().QuickStartBladeViewModel(container, initialState);
            };
            ViewModelFactoriesBase.prototype.Resource$QuickStartPartViewModel = function (container, initialState) {
                return this.Resource().QuickStartPartViewModel(container, initialState);
            };
            ViewModelFactoriesBase.prototype.Resource$SettingsBladeViewModel = function (container, initialState) {
                return this.Resource().SettingsBladeViewModel(container, initialState);
            };
            ViewModelFactoriesBase.prototype.Resource$SettingsPartViewModel = function (container, initialState) {
                return this.Resource().SettingsPartViewModel(container, initialState);
            };
            ViewModelFactoriesBase.prototype.Resource$BlankBladeBladeViewModel = function (container, initialState) {
                return this.Resource().BlankBladeBladeViewModel(container, initialState);
            };
            ViewModelFactoriesBase.prototype.Resource$OxfordCreateBladeViewModel = function (container, initialState) {
                return this.Resource().OxfordCreateBladeViewModel(container, initialState);
            };
            ViewModelFactoriesBase.prototype.Resource$OxfordApiTypeBladeViewModel = function (container, initialState) {
                return this.Resource().OxfordApiTypeBladeViewModel(container, initialState);
            };
            ViewModelFactoriesBase.prototype.Resource$EventsPartAdapterViewModel = function (container, initialState) {
                return this.Resource().EventsPartAdapterViewModel(container, initialState);
            };
            ViewModelFactoriesBase.prototype.Resource$PricingTierPartAdapterViewModel = function (container, initialState) {
                return this.Resource().PricingTierPartAdapterViewModel(container, initialState);
            };
            ViewModelFactoriesBase.prototype.Resource$ApiAccountPricingTierV3LauncherExtender = function (container, initialState) {
                return this.Resource().ApiAccountPricingTierV3LauncherExtender(container, initialState);
            };
            ViewModelFactoriesBase.prototype.Resource$SettingsCommandViewModel = function (container, initialState) {
                return this.Resource().SettingsCommandViewModel(container, initialState);
            };
            ViewModelFactoriesBase.prototype.Resource$DeleteCommandViewModel = function (container, initialState) {
                return this.Resource().DeleteCommandViewModel(container, initialState);
            };
            ViewModelFactoriesBase.prototype.Browse$AssetTypeViewModel = function (container, initialState) {
                return this.Browse().AssetTypeViewModel(container, initialState);
            };
            return ViewModelFactoriesBase;
        })();
        ViewModelFactories.ViewModelFactoriesBase = ViewModelFactoriesBase;
    })(ViewModelFactories || (ViewModelFactories = {}));
    return ViewModelFactories;
});
