/**
 * @file Source code generated by PDL compiler.
 */
/// <reference path="../../TypeReferences.d.ts" />
/// <amd-dependency path="../../Resource/Create/ViewModels/CreateBladeViewModel" />
define(["require", "exports", "../../Resource/Create/ViewModels/CreateBladeViewModel"], function (require, exports) {
    var Main;
    (function (Main) {
        "use strict";
        Main.blade = {
            "name": "CreateBlade",
            "viewModelName": "Resource$CreateBladeViewModel",
            "lenses": [],
            "width": 0,
            "style": 3,
            "actionBar": {
                "name": "",
                "actionBarKind": 1,
                "bindings": []
            },
            "templateBlade": {
                "htmlTemplate": "pdca665cc0cf193432299d7dc8d239dcd96",
                "parameterProvider": true,
                "partSize": 0
            }
        };
    })(Main || (Main = {}));
    return Main;
});
