/**
 * @file Source code generated by PDL compiler.
 */
/// <reference path="../../TypeReferences.d.ts" />
/// <amd-dependency path="../../Resource/Create/ViewModels/CreateBladeViewModel" />

import Icons = require ("../Shared/Icons");
import ClientResources = require ("ClientResources");
export = Main;
module Main {
    "use strict";
    export var blade: MsPortalFx.Extension.BladeDefinition = {
  "name": "CreateBlade",
  "viewModelName": "Resource$CreateBladeViewModel",
  "lenses": [],
  "width": 0,
  "style": 3,
  "actionBar": {
    "name": "",
    "actionBarKind": 1,
    "bindings": []
  },
  "templateBlade": {
    "htmlTemplate": "pdcdeeaa7d328384105beed33bbd439db1c",
    "parameterProvider": true,
    "partSize": 0
  }
};
}
