/**
 * @file Source code generated by PDL compiler.
 */
/// <reference path="../../TypeReferences.d.ts" />
/// <amd-dependency path="../../Resource/Settings/ViewModels/SettingsBladeViewModel" />
/// <amd-dependency path="../../Resource/Settings/ViewModels/SettingsPartViewModel" />

import Icons = require ("../Shared/Icons");
import ClientResources = require ("ClientResources");
export = Main;
module Main {
    "use strict";
    export var blade: MsPortalFx.Extension.BladeDefinition = {
  "name": "SettingsBlade",
  "inputs": [
    "id"
  ],
  "viewModelName": "Resource$SettingsBladeViewModel",
  "lenses": [
    {
      "name": "SettingListLens",
      "partInstances": [
        {
          "name": "SettingListPart",
          "inline": {
            "viewModel": "Resource$SettingsPartViewModel",
            "partKind": 0,
            "inputs": [
              "id"
            ],
            "bindings": [
              {
                "property": "id",
                "valuesFrom": [
                  {
                    "referenceType": 1,
                    "property": "id"
                  }
                ]
              }
            ],
            "htmlTemplate": "pdc76b430cee33d423f87878119b52b0474",
            "details": [
              {
                "invocationInputArguments": [
                  {
                    "valuesFrom": [
                      {
                        "referenceType": 0,
                        "property": "content.settingList.selectableData"
                      }
                    ]
                  }
                ]
              }
            ],
            "initialSize": 8,
            "supportedSizes": [
              8
            ],
            "viewStateProperties": [
              "content.settingList.selectableData.activatedItems",
              "content.settingList.selectableData.selectedItems"
            ]
          }
        }
      ]
    }
  ],
  "viewModelInputs": [
    {
      "property": "id",
      "valuesFrom": [
        {
          "referenceType": 1,
          "property": "id"
        }
      ]
    }
  ],
  "width": 0,
  "locked": true,
  "style": 11
};
}
