# This file is a standard requirement for Ibiza extensions. It changes the ItemType property of the .pde file to ExtensionReference after it has been installed. 
# Do not edit this file, or the nuget installation may fail.

param($installPath, $toolsPath, $package, $project)

# set the build action for the pde to ExtensionResource
$item = $project.ProjectItems.Item("Client").ProjectItems.Item("_extensions").ProjectItems.Item("AAD").ProjectItems.Item("Microsoft_Azure_AD.pde")
$item.Properties.Item("ItemType").Value = "ExtensionReference"

# launch the auxdoc
$DTE.ItemOperations.Navigate("http://aka.ms/portalfx/aadrbac") 