//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Portal.Extensions.ProjectOxfordExtension.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClientResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClientResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Portal.Extensions.ProjectOxfordExtension.Client.ClientResources", typeof(ClientResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API type.
        /// </summary>
        public static string ApiType {
            get {
                return ResourceManager.GetString("ApiType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distill actionable information from images..
        /// </summary>
        public static string ApiType_ComputerVision_Description {
            get {
                return ResourceManager.GetString("ApiType_ComputerVision_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Vision API.
        /// </summary>
        public static string ApiType_ComputerVision_Title {
            get {
                return ResourceManager.GetString("ApiType_ComputerVision_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalize experiences with emotion recognition..
        /// </summary>
        public static string ApiType_Emotion_Description {
            get {
                return ResourceManager.GetString("ApiType_Emotion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emotion API.
        /// </summary>
        public static string ApiType_Emotion_Title {
            get {
                return ResourceManager.GetString("ApiType_Emotion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect, identify, analyze, organize, and tag faces in photos..
        /// </summary>
        public static string ApiType_Face_Description {
            get {
                return ResourceManager.GetString("ApiType_Face_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face API.
        /// </summary>
        public static string ApiType_Face_Title {
            get {
                return ResourceManager.GetString("ApiType_Face_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teach your apps to understand commands from your users..
        /// </summary>
        public static string ApiType_LUIS_Description {
            get {
                return ResourceManager.GetString("ApiType_LUIS_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Understanding Intelligent Service (LUIS).
        /// </summary>
        public static string ApiType_LUIS_Title {
            get {
                return ResourceManager.GetString("ApiType_LUIS_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide personalized product recommendations for your customers..
        /// </summary>
        public static string ApiType_Recommendations_Subtitle {
            get {
                return ResourceManager.GetString("ApiType_Recommendations_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendations.
        /// </summary>
        public static string ApiType_Recommendations_Title {
            get {
                return ResourceManager.GetString("ApiType_Recommendations_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert speech to text and back again, and understand its intent..
        /// </summary>
        public static string ApiType_Speech_Description {
            get {
                return ResourceManager.GetString("ApiType_Speech_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech API.
        /// </summary>
        public static string ApiType_Speech_Title {
            get {
                return ResourceManager.GetString("ApiType_Speech_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect and correct common and uncommon spelling errors, via the Bing document index..
        /// </summary>
        public static string ApiType_SpellCheck_Description {
            get {
                return ResourceManager.GetString("ApiType_SpellCheck_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell check APIs.
        /// </summary>
        public static string ApiType_SpellCheck_Title {
            get {
                return ResourceManager.GetString("ApiType_SpellCheck_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Phrase Extraction.
        /// </summary>
        public static string ApiType_TextAnalytics_Features_KeyPhrase {
            get {
                return ResourceManager.GetString("ApiType_TextAnalytics_Features_KeyPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Detection.
        /// </summary>
        public static string ApiType_TextAnalytics_Features_LanguageDetection {
            get {
                return ResourceManager.GetString("ApiType_TextAnalytics_Features_LanguageDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentiment Analysis.
        /// </summary>
        public static string ApiType_TextAnalytics_Features_Sentiment {
            get {
                return ResourceManager.GetString("ApiType_TextAnalytics_Features_Sentiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic Detection.
        /// </summary>
        public static string ApiType_TextAnalytics_Features_TopicDetection {
            get {
                return ResourceManager.GetString("ApiType_TextAnalytics_Features_TopicDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect sentiment, key phrases, topics and language from your text..
        /// </summary>
        public static string ApiType_TextAnalytics_Subtitle {
            get {
                return ResourceManager.GetString("ApiType_TextAnalytics_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Analytics.
        /// </summary>
        public static string ApiType_TextAnalytics_Title {
            get {
                return ResourceManager.GetString("ApiType_TextAnalytics_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Detection.
        /// </summary>
        public static string ApiType_Video_FaceDetection_Description {
            get {
                return ResourceManager.GetString("ApiType_Video_FaceDetection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Face Detection API.
        /// </summary>
        public static string ApiType_Video_FaceDetection_Title {
            get {
                return ResourceManager.GetString("ApiType_Video_FaceDetection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion Detection.
        /// </summary>
        public static string ApiType_Video_MotionDetection_Description {
            get {
                return ResourceManager.GetString("ApiType_Video_MotionDetection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Motion Detection API.
        /// </summary>
        public static string ApiType_Video_MotionDetection_Title {
            get {
                return ResourceManager.GetString("ApiType_Video_MotionDetection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Understand and transform your videos..
        /// </summary>
        public static string ApiType_Video_Stabilization_Description {
            get {
                return ResourceManager.GetString("ApiType_Video_Stabilization_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Stabilization API.
        /// </summary>
        public static string ApiType_Video_Stabilization_Title {
            get {
                return ResourceManager.GetString("ApiType_Video_Stabilization_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leverage the power of language models trained on web-scale data..
        /// </summary>
        public static string ApiType_WebLM_Description {
            get {
                return ResourceManager.GetString("ApiType_WebLM_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Language Model API.
        /// </summary>
        public static string ApiType_WebLM_Title {
            get {
                return ResourceManager.GetString("ApiType_WebLM_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognitive Services is a set of services for understanding data and adding &apos;smart&apos; to your applications..
        /// </summary>
        public static string ApiTypeBlade_Description {
            get {
                return ResourceManager.GetString("ApiTypeBlade_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to project oxford api accounts.
        /// </summary>
        public static string AssetTypeNames_Resource_lowerPlural {
            get {
                return ResourceManager.GetString("AssetTypeNames_Resource_lowerPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to project oxford api account.
        /// </summary>
        public static string AssetTypeNames_Resource_lowerSingular {
            get {
                return ResourceManager.GetString("AssetTypeNames_Resource_lowerSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Oxford API accounts.
        /// </summary>
        public static string AssetTypeNames_Resource_plural {
            get {
                return ResourceManager.GetString("AssetTypeNames_Resource_plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Oxford API account.
        /// </summary>
        public static string AssetTypeNames_Resource_singular {
            get {
                return ResourceManager.GetString("AssetTypeNames_Resource_singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete account {0}.
        /// </summary>
        public static string BrowseBlade_DeleteResourceFail_Message {
            get {
                return ResourceManager.GetString("BrowseBlade_DeleteResourceFail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete account..
        /// </summary>
        public static string BrowseBlade_DeleteResourceFail_Title {
            get {
                return ResourceManager.GetString("BrowseBlade_DeleteResourceFail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting account {0}.
        /// </summary>
        public static string BrowseBlade_DeleteResourceInProgress_Message {
            get {
                return ResourceManager.GetString("BrowseBlade_DeleteResourceInProgress_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting account.
        /// </summary>
        public static string BrowseBlade_DeleteResourceInProgress_Title {
            get {
                return ResourceManager.GetString("BrowseBlade_DeleteResourceInProgress_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account {0} has been deleted successfully..
        /// </summary>
        public static string BrowseBlade_DeleteResourceSuccess_Message {
            get {
                return ResourceManager.GetString("BrowseBlade_DeleteResourceSuccess_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been deleted successfully..
        /// </summary>
        public static string BrowseBlade_DeleteResourceSuccess_Title {
            get {
                return ResourceManager.GetString("BrowseBlade_DeleteResourceSuccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognitive Services.
        /// </summary>
        public static string CognitiveServices {
            get {
                return ResourceManager.GetString("CognitiveServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognitive Services is a collection of APIs that enable natural and contextual interaction with tools that augment users&apos; experiences via the power of machine learnt models from Microsoft..
        /// </summary>
        public static string CognitiveServices_ApiTypeBlade_Description {
            get {
                return ResourceManager.GetString("CognitiveServices_ApiTypeBlade_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cognitive services accounts.
        /// </summary>
        public static string CognitiveServices_AssetTypeNames_Resource_lowerPlural {
            get {
                return ResourceManager.GetString("CognitiveServices_AssetTypeNames_Resource_lowerPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cognitive services account.
        /// </summary>
        public static string CognitiveServices_AssetTypeNames_Resource_lowerSingular {
            get {
                return ResourceManager.GetString("CognitiveServices_AssetTypeNames_Resource_lowerSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognitive Services accounts.
        /// </summary>
        public static string CognitiveServices_AssetTypeNames_Resource_plural {
            get {
                return ResourceManager.GetString("CognitiveServices_AssetTypeNames_Resource_plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognitive Services account.
        /// </summary>
        public static string CognitiveServices_AssetTypeNames_Resource_singular {
            get {
                return ResourceManager.GetString("CognitiveServices_AssetTypeNames_Resource_singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognitive Services account.
        /// </summary>
        public static string CognitiveServices_CreateBlade_Subtitle {
            get {
                return ResourceManager.GetString("CognitiveServices_CreateBlade_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CognitiveServices_CreateBlade_Title {
            get {
                return ResourceManager.GetString("CognitiveServices_CreateBlade_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognitive Services account.
        /// </summary>
        public static string CognitiveServices_ResourceBlade_Subtitle {
            get {
                return ResourceManager.GetString("CognitiveServices_ResourceBlade_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new resource group.
        /// </summary>
        public static string CreateBlade_CreateNewResourceGroup {
            get {
                return ResourceManager.GetString("CreateBlade_CreateNewResourceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name.
        /// </summary>
        public static string CreateBlade_EnterTheName {
            get {
                return ResourceManager.GetString("CreateBlade_EnterTheName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified resource name already exists in selected resource group and subscription..
        /// </summary>
        public static string CreateBlade_FormValidation_ResourceNameAlreadyExists {
            get {
                return ResourceManager.GetString("CreateBlade_FormValidation_ResourceNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreed.
        /// </summary>
        public static string CreateBlade_LegalTerm_Agreed {
            get {
                return ResourceManager.GetString("CreateBlade_LegalTerm_Agreed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognitive Services legal terms.
        /// </summary>
        public static string CreateBlade_LegalTerm_BladeTitle {
            get {
                return ResourceManager.GetString("CreateBlade_LegalTerm_BladeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Agree.
        /// </summary>
        public static string CreateBlade_LegalTerm_ButtonText {
            get {
                return ResourceManager.GetString("CreateBlade_LegalTerm_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review legal terms.
        /// </summary>
        public static string CreateBlade_LegalTerm_Description {
            get {
                return ResourceManager.GetString("CreateBlade_LegalTerm_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal terms.
        /// </summary>
        public static string CreateBlade_LegalTerm_Title {
            get {
                return ResourceManager.GetString("CreateBlade_LegalTerm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a location.
        /// </summary>
        public static string CreateBlade_PleaseSelectLocation {
            get {
                return ResourceManager.GetString("CreateBlade_PleaseSelectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select or enter a resource group.
        /// </summary>
        public static string CreateBlade_PleaseSelectResourceGroup {
            get {
                return ResourceManager.GetString("CreateBlade_PleaseSelectResourceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a subscription.
        /// </summary>
        public static string CreateBlade_PleaseSelectSubscription {
            get {
                return ResourceManager.GetString("CreateBlade_PleaseSelectSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your resource name can only include alphanumeric characters, ‘_,-’, and can’t end with ’_’ or ’-‘..
        /// </summary>
        public static string CreateBlade_ResourceNameInvalidMessage {
            get {
                return ResourceManager.GetString("CreateBlade_ResourceNameInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your resource name can only have 2 to 64 characters..
        /// </summary>
        public static string CreateBlade_ResourceNameLengthValidationMessage {
            get {
                return ResourceManager.GetString("CreateBlade_ResourceNameLengthValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your resource name should not be empty..
        /// </summary>
        public static string CreateBlade_ResourceNameRequired {
            get {
                return ResourceManager.GetString("CreateBlade_ResourceNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an API type.
        /// </summary>
        public static string CreateBlade_SelectApiType {
            get {
                return ResourceManager.GetString("CreateBlade_SelectApiType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a location.
        /// </summary>
        public static string CreateBlade_SelectLocation {
            get {
                return ResourceManager.GetString("CreateBlade_SelectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a resource group.
        /// </summary>
        public static string CreateBlade_SelectResourceGroup {
            get {
                return ResourceManager.GetString("CreateBlade_SelectResourceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a pricing tier.
        /// </summary>
        public static string CreateBlade_SelectSpec {
            get {
                return ResourceManager.GetString("CreateBlade_SelectSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a subscription.
        /// </summary>
        public static string CreateBlade_SelectSubscription {
            get {
                return ResourceManager.GetString("CreateBlade_SelectSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateBlade_Subtitle {
            get {
                return ResourceManager.GetString("CreateBlade_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognitive Services API account.
        /// </summary>
        public static string CreateBlade_Title {
            get {
                return ResourceManager.GetString("CreateBlade_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft_Azure_ProjectOxford.
        /// </summary>
        public static string ExtensionName {
            get {
                return ResourceManager.GetString("ExtensionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating....
        /// </summary>
        public static string KeyManagementBlade_GenKeyStateGenerateing {
            get {
                return ResourceManager.GetString("KeyManagementBlade_GenKeyStateGenerateing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success..
        /// </summary>
        public static string KeyManagementBlade_GenKeyStateSuccess {
            get {
                return ResourceManager.GetString("KeyManagementBlade_GenKeyStateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KEY 1.
        /// </summary>
        public static string KeyManagementBlade_Key1Title {
            get {
                return ResourceManager.GetString("KeyManagementBlade_Key1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KEY 2.
        /// </summary>
        public static string KeyManagementBlade_Key2Title {
            get {
                return ResourceManager.GetString("KeyManagementBlade_Key2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to regenerate the key 1?.
        /// </summary>
        public static string KeyManagementBlade_MsgBox_GenKey1Des {
            get {
                return ResourceManager.GetString("KeyManagementBlade_MsgBox_GenKey1Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerate Key 1.
        /// </summary>
        public static string KeyManagementBlade_MsgBox_GenKey1Title {
            get {
                return ResourceManager.GetString("KeyManagementBlade_MsgBox_GenKey1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to regenerate the key 2?.
        /// </summary>
        public static string KeyManagementBlade_MsgBox_GenKey2Des {
            get {
                return ResourceManager.GetString("KeyManagementBlade_MsgBox_GenKey2Des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerate Key 2.
        /// </summary>
        public static string KeyManagementBlade_MsgBox_GenKey2Title {
            get {
                return ResourceManager.GetString("KeyManagementBlade_MsgBox_GenKey2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to regenerate key.
        /// </summary>
        public static string KeyManagementBlade_RegenerateKeysCommand_FailureNotificationTitle {
            get {
                return ResourceManager.GetString("KeyManagementBlade_RegenerateKeysCommand_FailureNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerate Key1.
        /// </summary>
        public static string KeyManagementBlade_RegenerateKeysCommand_RegeneratePrimary {
            get {
                return ResourceManager.GetString("KeyManagementBlade_RegenerateKeysCommand_RegeneratePrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to regenerate primary key for {0}.
        /// </summary>
        public static string KeyManagementBlade_RegenerateKeysCommand_RegeneratePrimaryKeyConfirmMessage {
            get {
                return ResourceManager.GetString("KeyManagementBlade_RegenerateKeysCommand_RegeneratePrimaryKeyConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerate Key2.
        /// </summary>
        public static string KeyManagementBlade_RegenerateKeysCommand_RegenerateSecondary {
            get {
                return ResourceManager.GetString("KeyManagementBlade_RegenerateKeysCommand_RegenerateSecondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to regenerate secondary key for {0}.
        /// </summary>
        public static string KeyManagementBlade_RegenerateKeysCommand_RegenerateSecondaryKeyConfirmMessage {
            get {
                return ResourceManager.GetString("KeyManagementBlade_RegenerateKeysCommand_RegenerateSecondaryKeyConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerating access key ....
        /// </summary>
        public static string KeyManagementBlade_RegenerateKeysCommand_RegeneratingKeyInProgressTitle {
            get {
                return ResourceManager.GetString("KeyManagementBlade_RegenerateKeysCommand_RegeneratingKeyInProgressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully regenerated key.
        /// </summary>
        public static string KeyManagementBlade_RegenerateKeysCommand_SuccessNotificationTitle {
            get {
                return ResourceManager.GetString("KeyManagementBlade_RegenerateKeysCommand_SuccessNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerate Keys.
        /// </summary>
        public static string KeyManagementBlade_RegenerateKeysCommand_Title {
            get {
                return ResourceManager.GetString("KeyManagementBlade_RegenerateKeysCommand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage keys.
        /// </summary>
        public static string KeyManagementBlade_Title {
            get {
                return ResourceManager.GetString("KeyManagementBlade_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking “I Agree”, you acknowledge that the Microsoft Cognitive Services are in preview. You may use the Computer Vision API, Emotion API, Face API, Language Understanding Intelligent Service (LUIS), Bing Speech API, and Web Language Model in accordance with the use, privacy, data, security, and other terms in parts B, C, and D of the &lt;a target=&apos;_blank&apos; href=&apos;http://go.microsoft.com/fwlink/?LinkId=533207&apos;&gt;Microsoft Cognitive Services Preview Terms&lt;/a&gt;  and the &lt;a target=&apos;_blank&apos; href=&apos;http://go.microsof [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LegalBlade_Details {
            get {
                return ResourceManager.GetString("LegalBlade_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing tier.
        /// </summary>
        public static string PricingTier {
            get {
                return ResourceManager.GetString("PricingTier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string PricingTier_Basic {
            get {
                return ResourceManager.GetString("PricingTier_Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string PricingTier_Free {
            get {
                return ResourceManager.GetString("PricingTier_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium.
        /// </summary>
        public static string PricingTier_Premium {
            get {
                return ResourceManager.GetString("PricingTier_Premium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string PricingTier_Standard {
            get {
                return ResourceManager.GetString("PricingTier_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognitive Services.
        /// </summary>
        public static string ProjectOxford {
            get {
                return ResourceManager.GetString("ProjectOxford", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource ID.
        /// </summary>
        public static string PropertiesBlade_ResourceId {
            get {
                return ResourceManager.GetString("PropertiesBlade_ResourceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription ID.
        /// </summary>
        public static string PropertiesBlade_SubscriptionId {
            get {
                return ResourceManager.GetString("PropertiesBlade_SubscriptionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription name.
        /// </summary>
        public static string PropertiesBlade_SubscriptionName {
            get {
                return ResourceManager.GetString("PropertiesBlade_SubscriptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string PropertiesBlade_Title {
            get {
                return ResourceManager.GetString("PropertiesBlade_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Documentation .
        /// </summary>
        public static string QuickStartBlade_ApiDoc {
            get {
                return ResourceManager.GetString("QuickStartBlade_ApiDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Reference.
        /// </summary>
        public static string QuickStartBlade_ApiReference {
            get {
                return ResourceManager.GetString("QuickStartBlade_ApiReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API SDK.
        /// </summary>
        public static string QuickStartBlade_ApiSdk {
            get {
                return ResourceManager.GetString("QuickStartBlade_ApiSdk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Cognitive Services.
        /// </summary>
        public static string QuickStartBlade_CognitiveServices_About {
            get {
                return ResourceManager.GetString("QuickStartBlade_CognitiveServices_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string QuickStartBlade_Common_Title1 {
            get {
                return ResourceManager.GetString("QuickStartBlade_Common_Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started.
        /// </summary>
        public static string QuickStartBlade_Common_Title2 {
            get {
                return ResourceManager.GetString("QuickStartBlade_Common_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get free tools.
        /// </summary>
        public static string QuickStartBlade_Common_Title3 {
            get {
                return ResourceManager.GetString("QuickStartBlade_Common_Title3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn all about Cognitive Services APIs and how you can use them..
        /// </summary>
        public static string QuickStartBlade_ComputerVision_Description1 {
            get {
                return ResourceManager.GetString("QuickStartBlade_ComputerVision_Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get up to speed on how to use Computer Vision API..
        /// </summary>
        public static string QuickStartBlade_ComputerVision_Description2 {
            get {
                return ResourceManager.GetString("QuickStartBlade_ComputerVision_Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the SDK to build apps with Computer Vision API..
        /// </summary>
        public static string QuickStartBlade_ComputerVision_Description3 {
            get {
                return ResourceManager.GetString("QuickStartBlade_ComputerVision_Description3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer Code of Conduct.
        /// </summary>
        public static string QuickStartBlade_DeveloperCodeOfConduct {
            get {
                return ResourceManager.GetString("QuickStartBlade_DeveloperCodeOfConduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn all about Cognitive Services APIs and how you can use them..
        /// </summary>
        public static string QuickStartBlade_Emotion_Description1 {
            get {
                return ResourceManager.GetString("QuickStartBlade_Emotion_Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get up to speed on how to use Emotion API..
        /// </summary>
        public static string QuickStartBlade_Emotion_Description2 {
            get {
                return ResourceManager.GetString("QuickStartBlade_Emotion_Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the SDK to build apps with Emotion API..
        /// </summary>
        public static string QuickStartBlade_Emotion_Description3 {
            get {
                return ResourceManager.GetString("QuickStartBlade_Emotion_Description3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn all about Cognitive Services APIs and how you can use them..
        /// </summary>
        public static string QuickStartBlade_Face_Description1 {
            get {
                return ResourceManager.GetString("QuickStartBlade_Face_Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get up to speed on how to use Face API..
        /// </summary>
        public static string QuickStartBlade_Face_Description2 {
            get {
                return ResourceManager.GetString("QuickStartBlade_Face_Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the SDK to build apps with Face API..
        /// </summary>
        public static string QuickStartBlade_Face_Description3 {
            get {
                return ResourceManager.GetString("QuickStartBlade_Face_Description3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string QuickStartBlade_GetStarted {
            get {
                return ResourceManager.GetString("QuickStartBlade_GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live demos.
        /// </summary>
        public static string QuickStartBlade_LiveDemos {
            get {
                return ResourceManager.GetString("QuickStartBlade_LiveDemos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn all about Cognitive Services APIs and how you can use them..
        /// </summary>
        public static string QuickStartBlade_LUIS_Description1 {
            get {
                return ResourceManager.GetString("QuickStartBlade_LUIS_Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get up to speed on how to use LUIS..
        /// </summary>
        public static string QuickStartBlade_LUIS_Description2 {
            get {
                return ResourceManager.GetString("QuickStartBlade_LUIS_Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the SDK to build apps with LUIS..
        /// </summary>
        public static string QuickStartBlade_LUIS_Description3 {
            get {
                return ResourceManager.GetString("QuickStartBlade_LUIS_Description3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn about Cognitive Services APIs.
        /// </summary>
        public static string QuickStartBlade_Recommendations__Description1 {
            get {
                return ResourceManager.GetString("QuickStartBlade_Recommendations__Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get up to speed on how to use Recommendations..
        /// </summary>
        public static string QuickStartBlade_Recommendations_Description2 {
            get {
                return ResourceManager.GetString("QuickStartBlade_Recommendations_Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string QuickStartBlade_Recommendations_GetStarted {
            get {
                return ResourceManager.GetString("QuickStartBlade_Recommendations_GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Code.
        /// </summary>
        public static string QuickStartBlade_Recommendations_SampleCode {
            get {
                return ResourceManager.GetString("QuickStartBlade_Recommendations_SampleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn all about Cognitive Services APIs and how you can use them..
        /// </summary>
        public static string QuickStartBlade_Speech_Description1 {
            get {
                return ResourceManager.GetString("QuickStartBlade_Speech_Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get up to speed on how to use Speech API..
        /// </summary>
        public static string QuickStartBlade_Speech_Description2 {
            get {
                return ResourceManager.GetString("QuickStartBlade_Speech_Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the SDK to build apps with Speech API..
        /// </summary>
        public static string QuickStartBlade_Speech_Description3 {
            get {
                return ResourceManager.GetString("QuickStartBlade_Speech_Description3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn all about Cognitive Services APIs and how you can use them..
        /// </summary>
        public static string QuickStartBlade_SpellCheck_Description1 {
            get {
                return ResourceManager.GetString("QuickStartBlade_SpellCheck_Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get up to speed on how to use Spell Check API..
        /// </summary>
        public static string QuickStartBlade_SpellCheck_Description2 {
            get {
                return ResourceManager.GetString("QuickStartBlade_SpellCheck_Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the SDK to build apps with Spell Check API..
        /// </summary>
        public static string QuickStartBlade_SpellCheck_Description3 {
            get {
                return ResourceManager.GetString("QuickStartBlade_SpellCheck_Description3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn about Cognitive Services APIs.
        /// </summary>
        public static string QuickStartBlade_TextAnalytics__Description1 {
            get {
                return ResourceManager.GetString("QuickStartBlade_TextAnalytics__Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get up to speed on how to use Text Analytics..
        /// </summary>
        public static string QuickStartBlade_TextAnalytics_Description2 {
            get {
                return ResourceManager.GetString("QuickStartBlade_TextAnalytics_Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string QuickStartBlade_TextAnalytics_GetStarted {
            get {
                return ResourceManager.GetString("QuickStartBlade_TextAnalytics_GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Code.
        /// </summary>
        public static string QuickStartBlade_TextAnalytics_SampleCode {
            get {
                return ResourceManager.GetString("QuickStartBlade_TextAnalytics_SampleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try It Now.
        /// </summary>
        public static string QuickStartBlade_TextAnalytics_TryItNow {
            get {
                return ResourceManager.GetString("QuickStartBlade_TextAnalytics_TryItNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Start.
        /// </summary>
        public static string QuickStartBlade_Title {
            get {
                return ResourceManager.GetString("QuickStartBlade_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn all about Cognitive Services APIs and how you can use them..
        /// </summary>
        public static string QuickStartBlade_Video_FaceDetection_Description1 {
            get {
                return ResourceManager.GetString("QuickStartBlade_Video_FaceDetection_Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get up to speed on how to use Video APIs..
        /// </summary>
        public static string QuickStartBlade_Video_FaceDetection_Description2 {
            get {
                return ResourceManager.GetString("QuickStartBlade_Video_FaceDetection_Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the SDK to build apps with Video APIs..
        /// </summary>
        public static string QuickStartBlade_Video_FaceDetection_Description3 {
            get {
                return ResourceManager.GetString("QuickStartBlade_Video_FaceDetection_Description3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn all about Cognitive Services APIs and how you can use them..
        /// </summary>
        public static string QuickStartBlade_Video_MotionDetection_Description1 {
            get {
                return ResourceManager.GetString("QuickStartBlade_Video_MotionDetection_Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get up to speed on how to use Video APIs..
        /// </summary>
        public static string QuickStartBlade_Video_MotionDetection_Description2 {
            get {
                return ResourceManager.GetString("QuickStartBlade_Video_MotionDetection_Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the SDK to build apps with Video APIs..
        /// </summary>
        public static string QuickStartBlade_Video_MotionDetection_Description3 {
            get {
                return ResourceManager.GetString("QuickStartBlade_Video_MotionDetection_Description3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn all about Cognitive Services APIs and how you can use them..
        /// </summary>
        public static string QuickStartBlade_Video_Stabilization_Description1 {
            get {
                return ResourceManager.GetString("QuickStartBlade_Video_Stabilization_Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get up to speed on how to use Video APIs..
        /// </summary>
        public static string QuickStartBlade_Video_Stabilization_Description2 {
            get {
                return ResourceManager.GetString("QuickStartBlade_Video_Stabilization_Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the SDK to build apps with Video APIs..
        /// </summary>
        public static string QuickStartBlade_Video_Stabilization_Description3 {
            get {
                return ResourceManager.GetString("QuickStartBlade_Video_Stabilization_Description3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn all about Web Language Model APIs and how you can use them..
        /// </summary>
        public static string QuickStartBlade_WebLM__Description1 {
            get {
                return ResourceManager.GetString("QuickStartBlade_WebLM__Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get up to speed on how to use Web Language Model..
        /// </summary>
        public static string QuickStartBlade_WebLM_Description2 {
            get {
                return ResourceManager.GetString("QuickStartBlade_WebLM_Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the SDK to build apps with Web Language Model..
        /// </summary>
        public static string QuickStartBlade_WebLM_Description3 {
            get {
                return ResourceManager.GetString("QuickStartBlade_WebLM_Description3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to  delete it?.
        /// </summary>
        public static string ResourceBlade_DeleteCommand_Confirmation {
            get {
                return ResourceManager.GetString("ResourceBlade_DeleteCommand_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the resource....
        /// </summary>
        public static string ResourceBlade_DeleteCommand_Progress {
            get {
                return ResourceManager.GetString("ResourceBlade_DeleteCommand_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ResourceBlade_DeleteCommand_ResourceKey {
            get {
                return ResourceManager.GetString("ResourceBlade_DeleteCommand_ResourceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ResourceBlade_DeleteCommand_Title {
            get {
                return ResourceManager.GetString("ResourceBlade_DeleteCommand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint.
        /// </summary>
        public static string ResourceBlade_EndPoint {
            get {
                return ResourceManager.GetString("ResourceBlade_EndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string ResourceBlade_EventsInThePastWeekLauncherPartTitle {
            get {
                return ResourceManager.GetString("ResourceBlade_EventsInThePastWeekLauncherPartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string ResourceBlade_LensOperationsTitle {
            get {
                return ResourceManager.GetString("ResourceBlade_LensOperationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        public static string ResourceBlade_LensUsageTitle {
            get {
                return ResourceManager.GetString("ResourceBlade_LensUsageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        public static string ResourceBlade_MonitoringLensTitle {
            get {
                return ResourceManager.GetString("ResourceBlade_MonitoringLensTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing Tier.
        /// </summary>
        public static string ResourceBlade_PricingTierPartTitle {
            get {
                return ResourceManager.GetString("ResourceBlade_PricingTierPartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ResourceBlade_SettingsCommand_ResourceKey {
            get {
                return ResourceManager.GetString("ResourceBlade_SettingsCommand_ResourceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognitive Services API account.
        /// </summary>
        public static string ResourceBlade_Subtitle {
            get {
                return ResourceManager.GetString("ResourceBlade_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource group.
        /// </summary>
        public static string ResourceGroup {
            get {
                return ResourceManager.GetString("ResourceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name.
        /// </summary>
        public static string ResourceName {
            get {
                return ResourceManager.GetString("ResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert rules.
        /// </summary>
        public static string SettingsBlade_Alert {
            get {
                return ResourceManager.GetString("SettingsBlade_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit logs.
        /// </summary>
        public static string SettingsBlade_Audit {
            get {
                return ResourceManager.GetString("SettingsBlade_Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics.
        /// </summary>
        public static string SettingsBlade_Diagnostics {
            get {
                return ResourceManager.GetString("SettingsBlade_Diagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELP.
        /// </summary>
        public static string SettingsBlade_Group_Help {
            get {
                return ResourceManager.GetString("SettingsBlade_Group_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANAGE.
        /// </summary>
        public static string SettingsBlade_Group_Manage {
            get {
                return ResourceManager.GetString("SettingsBlade_Group_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONITOR.
        /// </summary>
        public static string SettingsBlade_Group_Monitor {
            get {
                return ResourceManager.GetString("SettingsBlade_Group_Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUPPORT &amp; TROUBLESHOOTING.
        /// </summary>
        public static string SettingsBlade_Group_Support {
            get {
                return ResourceManager.GetString("SettingsBlade_Group_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys.
        /// </summary>
        public static string SettingsBlade_Keys {
            get {
                return ResourceManager.GetString("SettingsBlade_Keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update pricing tier..
        /// </summary>
        public static string SettingsBlade_PricingTier_UpdateFail_Message {
            get {
                return ResourceManager.GetString("SettingsBlade_PricingTier_UpdateFail_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update pricing tier failed!.
        /// </summary>
        public static string SettingsBlade_PricingTier_UpdateFail_Title {
            get {
                return ResourceManager.GetString("SettingsBlade_PricingTier_UpdateFail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating pricing tier!.
        /// </summary>
        public static string SettingsBlade_PricingTier_UpdateProgress_Message {
            get {
                return ResourceManager.GetString("SettingsBlade_PricingTier_UpdateProgress_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress!.
        /// </summary>
        public static string SettingsBlade_PricingTier_UpdateProgress_Title {
            get {
                return ResourceManager.GetString("SettingsBlade_PricingTier_UpdateProgress_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing tier has been updated to {0} for resource {1}..
        /// </summary>
        public static string SettingsBlade_PricingTier_UpdateSuccess_Message {
            get {
                return ResourceManager.GetString("SettingsBlade_PricingTier_UpdateSuccess_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated pricing tier successfully!.
        /// </summary>
        public static string SettingsBlade_PricingTier_UpdateSuccess_Title {
            get {
                return ResourceManager.GetString("SettingsBlade_PricingTier_UpdateSuccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick start.
        /// </summary>
        public static string SettingsBlade_QuickStart {
            get {
                return ResourceManager.GetString("SettingsBlade_QuickStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New support request.
        /// </summary>
        public static string SettingsBlade_Support {
            get {
                return ResourceManager.GetString("SettingsBlade_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsBlade_Title {
            get {
                return ResourceManager.GetString("SettingsBlade_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troubleshoot.
        /// </summary>
        public static string SettingsBlade_Troubleshooting {
            get {
                return ResourceManager.GetString("SettingsBlade_Troubleshooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only create {0} {1} account(s) per API type per Azure subscription..
        /// </summary>
        public static string SpecCard_DisabledHelpMessage {
            get {
                return ResourceManager.GetString("SpecCard_DisabledHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribed.
        /// </summary>
        public static string SpecCard_DisabledMessage {
            get {
                return ResourceManager.GetString("SpecCard_DisabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse the available plans.
        /// </summary>
        public static string SpecPickerBlade_Subtitle {
            get {
                return ResourceManager.GetString("SpecPickerBlade_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your pricing tier.
        /// </summary>
        public static string SpecPickerBlade_Title {
            get {
                return ResourceManager.GetString("SpecPickerBlade_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Status_Active {
            get {
                return ResourceManager.GetString("Status_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provision canceled.
        /// </summary>
        public static string Status_ProvisionCanceled {
            get {
                return ResourceManager.GetString("Status_ProvisionCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provision failed.
        /// </summary>
        public static string Status_ProvisionFailed {
            get {
                return ResourceManager.GetString("Status_ProvisionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended.
        /// </summary>
        public static string Status_Suspended {
            get {
                return ResourceManager.GetString("Status_Suspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        public static string Subscription {
            get {
                return ResourceManager.GetString("Subscription", resourceCulture);
            }
        }
    }
}
