//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Portal.Extensions.ProjectOxfordExtension.Client
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClientResources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClientResources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Portal.Extensions.ProjectOxfordExtension.Client.ClientResources", typeof(ClientResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to API type.
        /// </summary>
        public static string ApiType
        {
            get
            {
                return ResourceManager.GetString("ApiType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Understand images and generate thumbnails..
        /// </summary>
        public static string ApiType_ComputerVision_Description
        {
            get
            {
                return ResourceManager.GetString("ApiType_ComputerVision_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ComputerVision.
        /// </summary>
        public static string ApiType_ComputerVision_Item
        {
            get
            {
                return ResourceManager.GetString("ApiType_ComputerVision_Item", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Computer Vision APIs.
        /// </summary>
        public static string ApiType_ComputerVision_Title
        {
            get
            {
                return ResourceManager.GetString("ApiType_ComputerVision_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Understand your users with Emotion Recognition..
        /// </summary>
        public static string ApiType_Emotion_Description
        {
            get
            {
                return ResourceManager.GetString("ApiType_Emotion_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Emotion.
        /// </summary>
        public static string ApiType_Emotion_Item
        {
            get
            {
                return ResourceManager.GetString("ApiType_Emotion_Item", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Emotion APIs.
        /// </summary>
        public static string ApiType_Emotion_Title
        {
            get
            {
                return ResourceManager.GetString("ApiType_Emotion_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to See your users with Face Detection and Recognition..
        /// </summary>
        public static string ApiType_Face_Description
        {
            get
            {
                return ResourceManager.GetString("ApiType_Face_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Face.
        /// </summary>
        public static string ApiType_Face_Item
        {
            get
            {
                return ResourceManager.GetString("ApiType_Face_Item", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Face APIs.
        /// </summary>
        public static string ApiType_Face_Title
        {
            get
            {
                return ResourceManager.GetString("ApiType_Face_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Understand natural language commands tailored to your application..
        /// </summary>
        public static string ApiType_LUIS_Description
        {
            get
            {
                return ResourceManager.GetString("ApiType_LUIS_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LUIS.
        /// </summary>
        public static string ApiType_LUIS_Item
        {
            get
            {
                return ResourceManager.GetString("ApiType_LUIS_Item", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Language Understanding Intelligent Service (LUIS).
        /// </summary>
        public static string ApiType_LUIS_Title
        {
            get
            {
                return ResourceManager.GetString("ApiType_LUIS_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Communicate with your users with speech recognition and synthesis powered by Bing..
        /// </summary>
        public static string ApiType_Speech_Description
        {
            get
            {
                return ResourceManager.GetString("ApiType_Speech_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Speech.
        /// </summary>
        public static string ApiType_Speech_Item
        {
            get
            {
                return ResourceManager.GetString("ApiType_Speech_Item", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Speech APIs.
        /// </summary>
        public static string ApiType_Speech_Title
        {
            get
            {
                return ResourceManager.GetString("ApiType_Speech_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Detect and correct common and uncommon spelling errors, via the Bing document index..
        /// </summary>
        public static string ApiType_SpellCheck_Description
        {
            get
            {
                return ResourceManager.GetString("ApiType_SpellCheck_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Spellcheck.
        /// </summary>
        public static string ApiType_SpellCheck_Item
        {
            get
            {
                return ResourceManager.GetString("ApiType_SpellCheck_Item", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Spell check APIs.
        /// </summary>
        public static string ApiType_SpellCheck_Title
        {
            get
            {
                return ResourceManager.GetString("ApiType_SpellCheck_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FaceDetection.
        /// </summary>
        public static string ApiType_Video_FaceDetection_Description
        {
            get
            {
                return ResourceManager.GetString("ApiType_Video_FaceDetection_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VideoFaceDetection.
        /// </summary>
        public static string ApiType_Video_FaceDetection_Item
        {
            get
            {
                return ResourceManager.GetString("ApiType_Video_FaceDetection_Item", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Video Face Detection API.
        /// </summary>
        public static string ApiType_Video_FaceDetection_Title
        {
            get
            {
                return ResourceManager.GetString("ApiType_Video_FaceDetection_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MotionDetection.
        /// </summary>
        public static string ApiType_Video_MotionDetection_Description
        {
            get
            {
                return ResourceManager.GetString("ApiType_Video_MotionDetection_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VideoMotionDetection.
        /// </summary>
        public static string ApiType_Video_MotionDetection_Item
        {
            get
            {
                return ResourceManager.GetString("ApiType_Video_MotionDetection_Item", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Video Motion Detection API.
        /// </summary>
        public static string ApiType_Video_MotionDetection_Title
        {
            get
            {
                return ResourceManager.GetString("ApiType_Video_MotionDetection_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Understand and transform your videos..
        /// </summary>
        public static string ApiType_Video_Stabilization_Description
        {
            get
            {
                return ResourceManager.GetString("ApiType_Video_Stabilization_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VideoStabilization.
        /// </summary>
        public static string ApiType_Video_Stabilization_Item
        {
            get
            {
                return ResourceManager.GetString("ApiType_Video_Stabilization_Item", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Video Stabilization API.
        /// </summary>
        public static string ApiType_Video_Stabilization_Title
        {
            get
            {
                return ResourceManager.GetString("ApiType_Video_Stabilization_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project Oxford is a set of services for understanding data and adding &apos;smart&apos; to your applications..
        /// </summary>
        public static string ApiTypeBlade_Description
        {
            get
            {
                return ResourceManager.GetString("ApiTypeBlade_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to project oxford api accounts.
        /// </summary>
        public static string AssetTypeNames_Resource_lowerPlural
        {
            get
            {
                return ResourceManager.GetString("AssetTypeNames_Resource_lowerPlural", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to project oxford api account.
        /// </summary>
        public static string AssetTypeNames_Resource_lowerSingular
        {
            get
            {
                return ResourceManager.GetString("AssetTypeNames_Resource_lowerSingular", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project Oxford API accounts.
        /// </summary>
        public static string AssetTypeNames_Resource_plural
        {
            get
            {
                return ResourceManager.GetString("AssetTypeNames_Resource_plural", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project Oxford API account.
        /// </summary>
        public static string AssetTypeNames_Resource_singular
        {
            get
            {
                return ResourceManager.GetString("AssetTypeNames_Resource_singular", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TODOCAS Cortana Analytics API desciption.
        /// </summary>
        public static string CortanaAnalytics_ApiTypeBlade_Description
        {
            get
            {
                return ResourceManager.GetString("CortanaAnalytics_ApiTypeBlade_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create a new resource group.
        /// </summary>
        public static string CreateBlade_CreateNewResourceGroup
        {
            get
            {
                return ResourceManager.GetString("CreateBlade_CreateNewResourceGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter the name.
        /// </summary>
        public static string CreateBlade_EnterTheName
        {
            get
            {
                return ResourceManager.GetString("CreateBlade_EnterTheName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Specified resource name already exists in selected resource group and subscription..
        /// </summary>
        public static string CreateBlade_FormValidation_ResourceNameAlreadyExists
        {
            get
            {
                return ResourceManager.GetString("CreateBlade_FormValidation_ResourceNameAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select a location.
        /// </summary>
        public static string CreateBlade_PleaseSelectLocation
        {
            get
            {
                return ResourceManager.GetString("CreateBlade_PleaseSelectLocation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select or enter a resource group.
        /// </summary>
        public static string CreateBlade_PleaseSelectResourceGroup
        {
            get
            {
                return ResourceManager.GetString("CreateBlade_PleaseSelectResourceGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select a subscription.
        /// </summary>
        public static string CreateBlade_PleaseSelectSubscription
        {
            get
            {
                return ResourceManager.GetString("CreateBlade_PleaseSelectSubscription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource name can only include alphanumeric characters, underscores and hyphens, and cannot end with underscore or hyphen..
        /// </summary>
        public static string CreateBlade_ResourceNameInvalidMessage
        {
            get
            {
                return ResourceManager.GetString("CreateBlade_ResourceNameInvalidMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource name only allows 2 to 64 characters..
        /// </summary>
        public static string CreateBlade_ResourceNameLengthValidationMessage
        {
            get
            {
                return ResourceManager.GetString("CreateBlade_ResourceNameLengthValidationMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The resource name is required.
        /// </summary>
        public static string CreateBlade_ResourceNameRequired
        {
            get
            {
                return ResourceManager.GetString("CreateBlade_ResourceNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select an API type.
        /// </summary>
        public static string CreateBlade_SelectApiType
        {
            get
            {
                return ResourceManager.GetString("CreateBlade_SelectApiType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a location.
        /// </summary>
        public static string CreateBlade_SelectLocation
        {
            get
            {
                return ResourceManager.GetString("CreateBlade_SelectLocation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a resource group.
        /// </summary>
        public static string CreateBlade_SelectResourceGroup
        {
            get
            {
                return ResourceManager.GetString("CreateBlade_SelectResourceGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a pricing tier.
        /// </summary>
        public static string CreateBlade_SelectSpec
        {
            get
            {
                return ResourceManager.GetString("CreateBlade_SelectSpec", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a subscription.
        /// </summary>
        public static string CreateBlade_SelectSubscription
        {
            get
            {
                return ResourceManager.GetString("CreateBlade_SelectSubscription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateBlade_Subtitle
        {
            get
            {
                return ResourceManager.GetString("CreateBlade_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project Oxford API account.
        /// </summary>
        public static string CreateBlade_Title
        {
            get
            {
                return ResourceManager.GetString("CreateBlade_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Microsoft_Azure_ProjectOxford.
        /// </summary>
        public static string ExtensionName
        {
            get
            {
                return ResourceManager.GetString("ExtensionName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Generating....
        /// </summary>
        public static string KeyManagementBlade_GenKeyStateGenerateing
        {
            get
            {
                return ResourceManager.GetString("KeyManagementBlade_GenKeyStateGenerateing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Success..
        /// </summary>
        public static string KeyManagementBlade_GenKeyStateSuccess
        {
            get
            {
                return ResourceManager.GetString("KeyManagementBlade_GenKeyStateSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to KEY 1.
        /// </summary>
        public static string KeyManagementBlade_Key1Title
        {
            get
            {
                return ResourceManager.GetString("KeyManagementBlade_Key1Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to KEY 2.
        /// </summary>
        public static string KeyManagementBlade_Key2Title
        {
            get
            {
                return ResourceManager.GetString("KeyManagementBlade_Key2Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to regenerate the key 1?.
        /// </summary>
        public static string KeyManagementBlade_MsgBox_GenKey1Des
        {
            get
            {
                return ResourceManager.GetString("KeyManagementBlade_MsgBox_GenKey1Des", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Regenerate Key 1.
        /// </summary>
        public static string KeyManagementBlade_MsgBox_GenKey1Title
        {
            get
            {
                return ResourceManager.GetString("KeyManagementBlade_MsgBox_GenKey1Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to regenerate the key 2?.
        /// </summary>
        public static string KeyManagementBlade_MsgBox_GenKey2Des
        {
            get
            {
                return ResourceManager.GetString("KeyManagementBlade_MsgBox_GenKey2Des", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Regenerate Key 2.
        /// </summary>
        public static string KeyManagementBlade_MsgBox_GenKey2Title
        {
            get
            {
                return ResourceManager.GetString("KeyManagementBlade_MsgBox_GenKey2Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Regenerate Key Failed.
        /// </summary>
        public static string KeyManagementBlade_RegenerateKeysCommand_FailureNotificationTitle
        {
            get
            {
                return ResourceManager.GetString("KeyManagementBlade_RegenerateKeysCommand_FailureNotificationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Regenerate Key1.
        /// </summary>
        public static string KeyManagementBlade_RegenerateKeysCommand_RegeneratePrimary
        {
            get
            {
                return ResourceManager.GetString("KeyManagementBlade_RegenerateKeysCommand_RegeneratePrimary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to regenerate the Primary key for {0}.
        /// </summary>
        public static string KeyManagementBlade_RegenerateKeysCommand_RegeneratePrimaryKeyConfirmMessage
        {
            get
            {
                return ResourceManager.GetString("KeyManagementBlade_RegenerateKeysCommand_RegeneratePrimaryKeyConfirmMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Regenerate Key2.
        /// </summary>
        public static string KeyManagementBlade_RegenerateKeysCommand_RegenerateSecondary
        {
            get
            {
                return ResourceManager.GetString("KeyManagementBlade_RegenerateKeysCommand_RegenerateSecondary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to regenerate the Secondary key for {0}.
        /// </summary>
        public static string KeyManagementBlade_RegenerateKeysCommand_RegenerateSecondaryKeyConfirmMessage
        {
            get
            {
                return ResourceManager.GetString("KeyManagementBlade_RegenerateKeysCommand_RegenerateSecondaryKeyConfirmMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Regenerating access key ....
        /// </summary>
        public static string KeyManagementBlade_RegenerateKeysCommand_RegeneratingKeyInProgressTitle
        {
            get
            {
                return ResourceManager.GetString("KeyManagementBlade_RegenerateKeysCommand_RegeneratingKeyInProgressTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Regenerate Key Successful.
        /// </summary>
        public static string KeyManagementBlade_RegenerateKeysCommand_SuccessNotificationTitle
        {
            get
            {
                return ResourceManager.GetString("KeyManagementBlade_RegenerateKeysCommand_SuccessNotificationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Regenerate Keys.
        /// </summary>
        public static string KeyManagementBlade_RegenerateKeysCommand_Title
        {
            get
            {
                return ResourceManager.GetString("KeyManagementBlade_RegenerateKeysCommand_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage keys.
        /// </summary>
        public static string KeyManagementBlade_Title
        {
            get
            {
                return ResourceManager.GetString("KeyManagementBlade_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingText
        {
            get
            {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location
        {
            get
            {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pricing tier.
        /// </summary>
        public static string PricingTier
        {
            get
            {
                return ResourceManager.GetString("PricingTier", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string PricingTier_Basic
        {
            get
            {
                return ResourceManager.GetString("PricingTier_Basic", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string PricingTier_Free
        {
            get
            {
                return ResourceManager.GetString("PricingTier_Free", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Premium.
        /// </summary>
        public static string PricingTier_Premium
        {
            get
            {
                return ResourceManager.GetString("PricingTier_Premium", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string PricingTier_Standard
        {
            get
            {
                return ResourceManager.GetString("PricingTier_Standard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project Oxford.
        /// </summary>
        public static string ProjectOxford
        {
            get
            {
                return ResourceManager.GetString("ProjectOxford", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource ID.
        /// </summary>
        public static string PropertiesBlade_ResourceId
        {
            get
            {
                return ResourceManager.GetString("PropertiesBlade_ResourceId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Subscription ID.
        /// </summary>
        public static string PropertiesBlade_SubscriptionId
        {
            get
            {
                return ResourceManager.GetString("PropertiesBlade_SubscriptionId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Subscription name.
        /// </summary>
        public static string PropertiesBlade_SubscriptionName
        {
            get
            {
                return ResourceManager.GetString("PropertiesBlade_SubscriptionName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string PropertiesBlade_Title
        {
            get
            {
                return ResourceManager.GetString("PropertiesBlade_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to API Reference.
        /// </summary>
        public static string QuickStartBlade_ApiReference
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_ApiReference", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string QuickStartBlade_Common_Title1
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_Common_Title1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Get started.
        /// </summary>
        public static string QuickStartBlade_Common_Title2
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_Common_Title2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Get free tools.
        /// </summary>
        public static string QuickStartBlade_Common_Title3
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_Common_Title3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Learn all about Project Oxford APIs and how you can use them..
        /// </summary>
        public static string QuickStartBlade_ComputerVision_Description1
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_ComputerVision_Description1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Get up to speed on how to use Computer Vision APIs..
        /// </summary>
        public static string QuickStartBlade_ComputerVision_Description2
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_ComputerVision_Description2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use the SDK to build apps with Computer Vision APIs..
        /// </summary>
        public static string QuickStartBlade_ComputerVision_Description3
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_ComputerVision_Description3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Developer Code of Conduct.
        /// </summary>
        public static string QuickStartBlade_DeveloperCodeOfConduct
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_DeveloperCodeOfConduct", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Learn all about Project Oxford APIs and how you can use them..
        /// </summary>
        public static string QuickStartBlade_Emotion_Description1
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_Emotion_Description1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Get up to speed on how to use Emotion APIs..
        /// </summary>
        public static string QuickStartBlade_Emotion_Description2
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_Emotion_Description2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use the SDK to build apps with Emotion APIs..
        /// </summary>
        public static string QuickStartBlade_Emotion_Description3
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_Emotion_Description3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Learn all about Project Oxford APIs and how you can use them..
        /// </summary>
        public static string QuickStartBlade_Face_Description1
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_Face_Description1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Get up to speed on how to use Face APIs..
        /// </summary>
        public static string QuickStartBlade_Face_Description2
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_Face_Description2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use the SDK to build apps with Face APIs..
        /// </summary>
        public static string QuickStartBlade_Face_Description3
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_Face_Description3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string QuickStartBlade_GetStarted
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_GetStarted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Live demos.
        /// </summary>
        public static string QuickStartBlade_LiveDemos
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_LiveDemos", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Learn all about Project Oxford APIs and how you can use them..
        /// </summary>
        public static string QuickStartBlade_LUIS_Description1
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_LUIS_Description1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Get up to speed on how to use LUIS..
        /// </summary>
        public static string QuickStartBlade_LUIS_Description2
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_LUIS_Description2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use the SDK to build apps with LUIS..
        /// </summary>
        public static string QuickStartBlade_LUIS_Description3
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_LUIS_Description3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Learn all about Project Oxford APIs and how you can use them..
        /// </summary>
        public static string QuickStartBlade_Speech_Description1
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_Speech_Description1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Get up to speed on how to use Speech APIs..
        /// </summary>
        public static string QuickStartBlade_Speech_Description2
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_Speech_Description2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use the SDK to build apps with Speech APIs..
        /// </summary>
        public static string QuickStartBlade_Speech_Description3
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_Speech_Description3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Learn all about Project Oxford APIs and how you can use them..
        /// </summary>
        public static string QuickStartBlade_SpellCheck_Description1
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_SpellCheck_Description1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Get up to speed on how to use Spell Check APIs..
        /// </summary>
        public static string QuickStartBlade_SpellCheck_Description2
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_SpellCheck_Description2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use the SDK to build apps with Spell Check APIs..
        /// </summary>
        public static string QuickStartBlade_SpellCheck_Description3
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_SpellCheck_Description3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quick Start.
        /// </summary>
        public static string QuickStartBlade_Title
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Learn all about Project Oxford APIs and how you can use them..
        /// </summary>
        public static string QuickStartBlade_Video_FaceDetection_Description1
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_Video_FaceDetection_Description1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Get up to speed on how to use Video APIs..
        /// </summary>
        public static string QuickStartBlade_Video_FaceDetection_Description2
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_Video_FaceDetection_Description2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use the SDK to build apps with Video APIs..
        /// </summary>
        public static string QuickStartBlade_Video_FaceDetection_Description3
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_Video_FaceDetection_Description3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Learn all about Project Oxford APIs and how you can use them..
        /// </summary>
        public static string QuickStartBlade_Video_MotionDetection_Description1
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_Video_MotionDetection_Description1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Get up to speed on how to use Video APIs..
        /// </summary>
        public static string QuickStartBlade_Video_MotionDetection_Description2
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_Video_MotionDetection_Description2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use the SDK to build apps with Video APIs..
        /// </summary>
        public static string QuickStartBlade_Video_MotionDetection_Description3
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_Video_MotionDetection_Description3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Learn all about Project Oxford APIs and how you can use them..
        /// </summary>
        public static string QuickStartBlade_Video_Stabilization_Description1
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_Video_Stabilization_Description1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Get up to speed on how to use Video APIs..
        /// </summary>
        public static string QuickStartBlade_Video_Stabilization_Description2
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_Video_Stabilization_Description2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use the SDK to build apps with Video APIs..
        /// </summary>
        public static string QuickStartBlade_Video_Stabilization_Description3
        {
            get
            {
                return ResourceManager.GetString("QuickStartBlade_Video_Stabilization_Description3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region
        {
            get
            {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete?.
        /// </summary>
        public static string ResourceBlade_DeleteCommand_Confirmation
        {
            get
            {
                return ResourceManager.GetString("ResourceBlade_DeleteCommand_Confirmation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deleting the resource....
        /// </summary>
        public static string ResourceBlade_DeleteCommand_Progress
        {
            get
            {
                return ResourceManager.GetString("ResourceBlade_DeleteCommand_Progress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ResourceBlade_DeleteCommand_ResourceKey
        {
            get
            {
                return ResourceManager.GetString("ResourceBlade_DeleteCommand_ResourceKey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ResourceBlade_DeleteCommand_Title
        {
            get
            {
                return ResourceManager.GetString("ResourceBlade_DeleteCommand_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to End point.
        /// </summary>
        public static string ResourceBlade_EndPoint
        {
            get
            {
                return ResourceManager.GetString("ResourceBlade_EndPoint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string ResourceBlade_EventsInThePastWeekLauncherPartTitle
        {
            get
            {
                return ResourceManager.GetString("ResourceBlade_EventsInThePastWeekLauncherPartTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string ResourceBlade_LensOperationsTitle
        {
            get
            {
                return ResourceManager.GetString("ResourceBlade_LensOperationsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        public static string ResourceBlade_MonitoringLensTitle
        {
            get
            {
                return ResourceManager.GetString("ResourceBlade_MonitoringLensTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ResourceBlade_SettingsCommand_ResourceKey
        {
            get
            {
                return ResourceManager.GetString("ResourceBlade_SettingsCommand_ResourceKey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Project Oxford API account.
        /// </summary>
        public static string ResourceBlade_Subtitle
        {
            get
            {
                return ResourceManager.GetString("ResourceBlade_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource group.
        /// </summary>
        public static string ResourceGroup
        {
            get
            {
                return ResourceManager.GetString("ResourceGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource name.
        /// </summary>
        public static string ResourceName
        {
            get
            {
                return ResourceManager.GetString("ResourceName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alert rules.
        /// </summary>
        public static string SettingsBlade_Alert
        {
            get
            {
                return ResourceManager.GetString("SettingsBlade_Alert", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Audit logs.
        /// </summary>
        public static string SettingsBlade_Audit
        {
            get
            {
                return ResourceManager.GetString("SettingsBlade_Audit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Diagnostics.
        /// </summary>
        public static string SettingsBlade_Diagnostics
        {
            get
            {
                return ResourceManager.GetString("SettingsBlade_Diagnostics", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to HELP.
        /// </summary>
        public static string SettingsBlade_Group_Help
        {
            get
            {
                return ResourceManager.GetString("SettingsBlade_Group_Help", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MANAGE.
        /// </summary>
        public static string SettingsBlade_Group_Manage
        {
            get
            {
                return ResourceManager.GetString("SettingsBlade_Group_Manage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MONITOR.
        /// </summary>
        public static string SettingsBlade_Group_Monitor
        {
            get
            {
                return ResourceManager.GetString("SettingsBlade_Group_Monitor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SUPPORT &amp; TROUBLESHOOTING.
        /// </summary>
        public static string SettingsBlade_Group_Support
        {
            get
            {
                return ResourceManager.GetString("SettingsBlade_Group_Support", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Keys.
        /// </summary>
        public static string SettingsBlade_Keys
        {
            get
            {
                return ResourceManager.GetString("SettingsBlade_Keys", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to update pricing tier!.
        /// </summary>
        public static string SettingsBlade_PricingTier_UpdateFail_Message
        {
            get
            {
                return ResourceManager.GetString("SettingsBlade_PricingTier_UpdateFail_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update pricing tier failed!.
        /// </summary>
        public static string SettingsBlade_PricingTier_UpdateFail_Title
        {
            get
            {
                return ResourceManager.GetString("SettingsBlade_PricingTier_UpdateFail_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Updating pricing tier!.
        /// </summary>
        public static string SettingsBlade_PricingTier_UpdateProgress_Message
        {
            get
            {
                return ResourceManager.GetString("SettingsBlade_PricingTier_UpdateProgress_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to In progress!.
        /// </summary>
        public static string SettingsBlade_PricingTier_UpdateProgress_Title
        {
            get
            {
                return ResourceManager.GetString("SettingsBlade_PricingTier_UpdateProgress_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pricing tier has been updated to {0} for resource {1}..
        /// </summary>
        public static string SettingsBlade_PricingTier_UpdateSuccess_Message
        {
            get
            {
                return ResourceManager.GetString("SettingsBlade_PricingTier_UpdateSuccess_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Updated pricing tier successfully!.
        /// </summary>
        public static string SettingsBlade_PricingTier_UpdateSuccess_Title
        {
            get
            {
                return ResourceManager.GetString("SettingsBlade_PricingTier_UpdateSuccess_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quick start.
        /// </summary>
        public static string SettingsBlade_QuickStart
        {
            get
            {
                return ResourceManager.GetString("SettingsBlade_QuickStart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New support request.
        /// </summary>
        public static string SettingsBlade_Support
        {
            get
            {
                return ResourceManager.GetString("SettingsBlade_Support", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsBlade_Title
        {
            get
            {
                return ResourceManager.GetString("SettingsBlade_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Troubleshoot.
        /// </summary>
        public static string SettingsBlade_Troubleshooting
        {
            get
            {
                return ResourceManager.GetString("SettingsBlade_Troubleshooting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Browse the available plans.
        /// </summary>
        public static string SpecPickerBlade_Subtitle
        {
            get
            {
                return ResourceManager.GetString("SpecPickerBlade_Subtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose your pricing tier.
        /// </summary>
        public static string SpecPickerBlade_Title
        {
            get
            {
                return ResourceManager.GetString("SpecPickerBlade_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status
        {
            get
            {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Status_Active
        {
            get
            {
                return ResourceManager.GetString("Status_Active", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Provision canceled.
        /// </summary>
        public static string Status_ProvisionCanceled
        {
            get
            {
                return ResourceManager.GetString("Status_ProvisionCanceled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Provision failed.
        /// </summary>
        public static string Status_ProvisionFailed
        {
            get
            {
                return ResourceManager.GetString("Status_ProvisionFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Suspended.
        /// </summary>
        public static string Status_Suspended
        {
            get
            {
                return ResourceManager.GetString("Status_Suspended", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        public static string Subscription
        {
            get
            {
                return ResourceManager.GetString("Subscription", resourceCulture);
            }
        }
    }
}
